### PR TITLE
Added Support for KMS Encryption

### PR DESCRIPTION
**Pull request by aaronsteers**
This PR is to address #5.

I'm posting here in draft stage in order to get early feedback on the proposed config params.

From the newly updated/proposed README.md:

| Property                            | Type    | Required?  | Description                                                   |
|-------------------------------------|---------|------------|---------------------------------------------------------------|
| encryption_type                     | String  | No         | (Default: 'none') The type of encryption to use. Current supported options are: 'none' and 'KMS'.
| encryption_key                      | String  | No         | A reference to the encryption key to use for data encryption. For KMS encryption, this should be the name of the KMS encryption key. This field is ignored if 'encryption_type' is none or blank. |

### CODE REVIEW

**Comment by aaronsteers** [comment]
Update: the code is feature complete but not tested. No known issues, but I will report back after some testing...

**Comment by aaronsteers** [comment]
Initial testing is complete:

Tests performed:

1. Run the tap with no encryption settings. **Output:** successful.
2. Run the tap with encryption_type = 'kms'. **Output:** successful upload, confirmed in console that S3 file has kms encryption using the default key.
3. Run the tap with encryption_type = 'kms' and encryption_key is a newly created ID of a KMS key generated through the AWS console. **Output:** successful upload, confirmed in console that S3 file has kms encryption using the specified key ID.


**Other notes:**
 * I found and resolve an unrelated bug where if 's3_path_prefix' were omitted, it would default to the text prefix 'None' on all files.
 * Client config now specifies to use 's3v4' auth protocol for all uploads. This should not have any averse affects but I'm calling it out here for transparency.

**Comment by koszti** [comment]
thanks @aaronsteers . This looks fine but can you please resolve the conflicts cause by merging https://github.com/transferwise/pipelinewise-target-s3-csv/commit/37dc0895d0c583d15253e5c7bbaa9f47b4b0fc77 ?

**Comment by aaronsteers** [comment]
Hi, @koszti . Thanks very much for the review. I've merged in the latest from master so this is now up-to-date.

**Pull request merged**
